In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential
from tensorflow.keras import optimizers
from tensorflow.keras.layers import Dense
from tensorflow.keras import regularizers


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import KFold
from sklearn.metrics import ConfusionMatrixDisplay

In [2]:
#load the data
df = pd.read_csv('sudo model 1.csv')
df.head()

Unnamed: 0 Result  Target  PR_Interval  RR_Interval  RS_Interval
0           1      j       1     0.000000     0.000000  3699.119444
1           2      N       0     0.052778     0.108333     0.230556
2           3  (AFIB       1     0.077778     0.300000 -4136.461111
3           4      j       1     0.000000     0.000000  3924.050000
4           5   (AFL       1     0.061111     0.119444     0.244444

In [3]:
df = df[["Result", "PR_Interval", "RR_Interval", "RS_Interval"]]
df.head()

Result  PR_Interval  RR_Interval  RS_Interval
0      j     0.000000     0.000000  3699.119444
1      N     0.052778     0.108333     0.230556
2  (AFIB     0.077778     0.300000 -4136.461111
3      j     0.000000     0.000000  3924.050000
4   (AFL     0.061111     0.119444     0.244444

In [4]:
#seperate input and output
X,y = df.iloc[:, 1:], df.iloc[:, 0]
#m\change outputs into numbers
le = LabelEncoder()
le.fit(y)
y = le.transform(y)

#seperate training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [5]:
#define the model
#model = Sequential()
#model.add(Dense(3, activation='relu', use_bias=True, kernel_regularizer = keras.regularizers.l1_l2(l1=0.01, l2=0.01),
#               bias_regularizer='l2', activity_regularizer='l2', input_shape=(3,)))
#model.add(Dense(10, activation='relu', use_bias=True, kernel_regularizer = keras.regularizers.l1_l2(l1=0.01, l2=0.01),
 #              bias_regularizer='l2', activity_regularizer='l2'))
#model.add(Dense(50, activation='relu', use_bias=True, kernel_regularizer = keras.regularizers.l1_l2(l1=0.01, l2=0.01),
#               bias_regularizer='l2', activity_regularizer='l2'))
#model.add(Dense(50, activation='relu', use_bias=True, kernel_regularizer = keras.regularizers.l1_l2(l1=0.01, l2=0.01),
#               bias_regularizer='l2', activity_regularizer='l2'))
#model.add(Dense(10, activation='relu', use_bias=True, kernel_regularizer = keras.regularizers.l1_l2(l1=0.01, l2=0.01),
#               bias_regularizer='l2', activity_regularizer='l2'))
#model.add(Dense(5, activation='softmax'))

model = Sequential()
model.add(Dense(48, activation='relu', use_bias=True, kernel_regularizer = keras.regularizers.l1_l2(l1=0.01, l2=0.01),
               bias_regularizer='l2', activity_regularizer='l2', input_shape=(3,)))

model.add(Dense(24, activation='relu', use_bias=True, kernel_regularizer = keras.regularizers.l1_l2(l1=0.01, l2=0.01),
               bias_regularizer='l2', activity_regularizer='l2'))

model.add(Dense(12, activation='relu', use_bias=True, kernel_regularizer = keras.regularizers.l1_l2(l1=0.01, l2=0.01),
               bias_regularizer='l2', activity_regularizer='l2'))

model.add(Dense(5, activation='softmax'))

In [6]:
#complie the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [7]:
#fit the model
model.fit(X, y, epochs=100, batch_size=50, verbose=2)

Epoch 1/100
11/11 - 0s - loss: 83825.2266 - accuracy: 0.0854 - 446ms/epoch - 41ms/step
Epoch 2/100
11/11 - 0s - loss: 67820.9219 - accuracy: 0.1845 - 8ms/epoch - 682us/step
Epoch 3/100
11/11 - 0s - loss: 56608.4375 - accuracy: 0.2214 - 7ms/epoch - 636us/step
Epoch 4/100
11/11 - 0s - loss: 49053.1094 - accuracy: 0.2524 - 7ms/epoch - 591us/step
Epoch 5/100
11/11 - 0s - loss: 43077.7656 - accuracy: 0.2252 - 7ms/epoch - 636us/step
Epoch 6/100
11/11 - 0s - loss: 38347.0664 - accuracy: 0.2194 - 7ms/epoch - 636us/step
Epoch 7/100
11/11 - 0s - loss: 34771.5430 - accuracy: 0.2194 - 7ms/epoch - 591us/step
Epoch 8/100
11/11 - 0s - loss: 31465.5488 - accuracy: 0.2214 - 7ms/epoch - 591us/step
Epoch 9/100
11/11 - 0s - loss: 28648.7695 - accuracy: 0.2252 - 7ms/epoch - 636us/step
Epoch 10/100
11/11 - 0s - loss: 26098.0527 - accuracy: 0.2932 - 7ms/epoch - 636us/step
Epoch 11/100
11/11 - 0s - loss: 23857.7930 - accuracy: 0.2388 - 7ms/epoch - 636us/step
Epoch 12/100
11/11 - 0s - loss: 21761.1035 - accura

Epoch 97/100
11/11 - 0s - loss: 60.8577 - accuracy: 0.4447 - 6ms/epoch - 591us/step
Epoch 98/100
11/11 - 0s - loss: 59.6891 - accuracy: 0.4447 - 7ms/epoch - 591us/step
Epoch 99/100
11/11 - 0s - loss: 59.4102 - accuracy: 0.4447 - 7ms/epoch - 591us/step
Epoch 100/100
11/11 - 0s - loss: 57.7983 - accuracy: 0.4447 - 7ms/epoch - 591us/step


In [8]:
# evaluate the model
loss = model.evaluate(X, y, verbose=True)

17/17 [==============================] - 0s 563us/step - loss: 56.8207 - accuracy: 0.4447


In [9]:
prediction = model.predict(X_test)
print(prediction)

[[0.197588   0.1101044  0.16301121 0.11834389 0.41095254]
 [0.197588   0.1101044  0.16301121 0.11834389 0.41095254]
 [0.20138395 0.1109312  0.16653071 0.11757686 0.40357727]
 [0.197588   0.1101044  0.16301121 0.11834389 0.41095254]
 [0.20322189 0.11126102 0.16686578 0.11711368 0.4015376 ]
 [0.197588   0.1101044  0.16301121 0.11834389 0.41095254]
 [0.18180625 0.10452277 0.13974017 0.10382967 0.4701012 ]
 [0.197588   0.1101044  0.16301121 0.11834389 0.41095254]
 [0.2009823  0.1108451  0.16615763 0.11765928 0.40435562]
 [0.197588   0.1101044  0.16301121 0.11834389 0.41095254]
 [0.20167224 0.11098585 0.16664253 0.11750783 0.40319154]
 [0.20146988 0.11094958 0.16661055 0.11755921 0.4034108 ]
 [0.197588   0.1101044  0.16301121 0.11834389 0.41095254]
 [0.197588   0.1101044  0.16301121 0.11834389 0.41095254]
 [0.20124015 0.11090041 0.16639711 0.11760641 0.40385595]
 [0.20317984 0.11125358 0.16685978 0.11712436 0.4015824 ]
 [0.197588   0.1101044  0.16301121 0.11834389 0.41095254]
 [0.197588   0

In [10]:
y_pred=np.argmax(prediction, axis=1)
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[ 0  0  0  0 21]
 [ 0  0  0  0 14]
 [ 0  0  0  0 12]
 [ 0  0  0  0 11]
 [ 0  0  0  0 45]]
