In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.metrics import confusion_matrix

In [2]:
#load the data
df = pd.read_csv('Model 1.csv')
df.head()

Result    0    3    6    9    12    15    18    21    24  ...   258   261  \
0      N  967  967  966  978   970   970   965   971   962  ...   966   967   
1      N  987  981  984  980   981   980   979   981   981  ...  1004   995   
2      N  969  972  986  991  1004  1006  1013  1011  1014  ...  1015  1012   
3      N  954  960  951  951   951   952   951   949   946  ...   969   974   
4      Q  986  988  985  985   984   987   983   984   983  ...   973   983   

    264   267   270   273   276   279   282   285  
0   961   961   969   961   966   964   960   958  
1   986   967   969   961   957   957   955   951  
2  1015  1008  1007  1001  1006  1001  1009  1007  
3   973   981   974   977   969   977   975   976  
4   983   990   994   997   996  1001   996   998  

[5 rows x 97 columns]

In [3]:
#seperate input and output
X,y = df.iloc[:, 1:], df.iloc[:, 0]
#m\change outputs into numbers
le = LabelEncoder()
le.fit(y)
y = le.transform(y)

#seperate training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [4]:
#define the model
model = Sequential()
model.add(Dense(3, activation='relu', use_bias=True, input_shape=(96,)))
model.add(Dense(10, activation='relu', use_bias=True))
model.add(Dense(40, activation='relu', use_bias=True))
model.add(Dense(40, activation='relu', use_bias=True))
model.add(Dense(10, activation='relu', use_bias=True))
model.add(Dense(5, activation='softmax'))

In [5]:
#complie
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['Accuracy'])

In [6]:
#fit the model
model.fit(X, y, epochs=200, batch_size=100, verbose=2)

Epoch 1/200
320/320 - 3s - loss: 8.6382 - Accuracy: 0.4007 - 3s/epoch - 9ms/step
Epoch 2/200
320/320 - 1s - loss: 1.3637 - Accuracy: 0.4093 - 1s/epoch - 3ms/step
Epoch 3/200
320/320 - 1s - loss: 1.3548 - Accuracy: 0.4093 - 1s/epoch - 4ms/step
Epoch 4/200
320/320 - 1s - loss: 1.3546 - Accuracy: 0.4093 - 1s/epoch - 4ms/step
Epoch 5/200
320/320 - 1s - loss: 1.3549 - Accuracy: 0.4093 - 1s/epoch - 4ms/step
Epoch 6/200
320/320 - 1s - loss: 1.3549 - Accuracy: 0.4093 - 1s/epoch - 3ms/step
Epoch 7/200
320/320 - 1s - loss: 1.3547 - Accuracy: 0.4093 - 1s/epoch - 4ms/step
Epoch 8/200
320/320 - 1s - loss: 1.3546 - Accuracy: 0.4093 - 1s/epoch - 4ms/step
Epoch 9/200
320/320 - 1s - loss: 1.3548 - Accuracy: 0.4093 - 1s/epoch - 3ms/step
Epoch 10/200
320/320 - 1s - loss: 1.3549 - Accuracy: 0.4093 - 1s/epoch - 3ms/step
Epoch 11/200
320/320 - 1s - loss: 1.3549 - Accuracy: 0.4093 - 808ms/epoch - 3ms/step
Epoch 12/200
320/320 - 1s - loss: 1.3550 - Accuracy: 0.4093 - 1s/epoch - 4ms/step
Epoch 13/200
320/320 -

Epoch 101/200
320/320 - 1s - loss: 1.3548 - Accuracy: 0.4093 - 1s/epoch - 4ms/step
Epoch 102/200
320/320 - 1s - loss: 1.3549 - Accuracy: 0.4093 - 1s/epoch - 4ms/step
Epoch 103/200
320/320 - 1s - loss: 1.3549 - Accuracy: 0.4093 - 776ms/epoch - 2ms/step
Epoch 104/200
320/320 - 1s - loss: 1.3548 - Accuracy: 0.4093 - 885ms/epoch - 3ms/step
Epoch 105/200
320/320 - 1s - loss: 1.3548 - Accuracy: 0.4093 - 983ms/epoch - 3ms/step
Epoch 106/200
320/320 - 1s - loss: 1.3548 - Accuracy: 0.4093 - 985ms/epoch - 3ms/step
Epoch 107/200
320/320 - 1s - loss: 1.3548 - Accuracy: 0.4093 - 1s/epoch - 4ms/step
Epoch 108/200
320/320 - 1s - loss: 1.3548 - Accuracy: 0.4093 - 905ms/epoch - 3ms/step
Epoch 109/200
320/320 - 1s - loss: 1.3547 - Accuracy: 0.4093 - 971ms/epoch - 3ms/step
Epoch 110/200
320/320 - 1s - loss: 1.3548 - Accuracy: 0.4093 - 1s/epoch - 4ms/step
Epoch 111/200
320/320 - 1s - loss: 1.3548 - Accuracy: 0.4093 - 1s/epoch - 4ms/step
Epoch 112/200
320/320 - 1s - loss: 1.3547 - Accuracy: 0.4093 - 785ms/

Epoch 199/200
320/320 - 1s - loss: 1.3547 - Accuracy: 0.4093 - 1s/epoch - 3ms/step
Epoch 200/200
320/320 - 1s - loss: 1.3547 - Accuracy: 0.4093 - 987ms/epoch - 3ms/step


In [7]:
# evaluate the model
loss = model.evaluate(X, y, verbose=True)

998/998 [==============================] - 3s 3ms/step - loss: 1.3548 - Accuracy: 0.4093


In [8]:
prediction = model.predict(X_test)
print(prediction)

[[0.02427989 0.42147782 0.24454117 0.08555445 0.22414666]
 [0.02427989 0.42147782 0.24454117 0.08555445 0.22414666]
 [0.02427989 0.42147782 0.24454117 0.08555445 0.22414666]
 ...
 [0.02427989 0.42147782 0.24454117 0.08555445 0.22414666]
 [0.02427989 0.42147782 0.24454117 0.08555445 0.22414666]
 [0.02427989 0.42147782 0.24454117 0.08555445 0.22414666]]


In [9]:
confusion_matrix(y_test, prediction)

ValueError: Classification metrics can't handle a mix of multiclass and continuous-multioutput targets