In [1]:
#from numpy.random import seed
#seed(1)
#from tensorflow import random
#random.set_seed(2)

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import keras
from tensorflow.keras import layers
from tensorflow.keras import Sequential
from tensorflow.keras import optimizers
from tensorflow.keras.layers import Dense
from tensorflow.keras import regularizers


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import KFold
from sklearn.metrics import ConfusionMatrixDisplay

In [3]:
#load the data
df = pd.read_csv('Model 1.csv')
df.head()

Result    0    3    6    9    12    15    18    21    24  ...   258   261  \
0      N  967  967  966  978   970   970   965   971   962  ...   966   967   
1      N  987  981  984  980   981   980   979   981   981  ...  1004   995   
2      N  969  972  986  991  1004  1006  1013  1011  1014  ...  1015  1012   
3      N  954  960  951  951   951   952   951   949   946  ...   969   974   
4      Q  986  988  985  985   984   987   983   984   983  ...   973   983   

    264   267   270   273   276   279   282   285  
0   961   961   969   961   966   964   960   958  
1   986   967   969   961   957   957   955   951  
2  1015  1008  1007  1001  1006  1001  1009  1007  
3   973   981   974   977   969   977   975   976  
4   983   990   994   997   996  1001   996   998  

[5 rows x 97 columns]

In [4]:
#seperate input and output
X,y = df.iloc[:, 1:], df.iloc[:, 0]
#m\change outputs into numbers
le = LabelEncoder()
le.fit(y)
y = le.transform(y)

#seperate training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
#k fold cross validation
#kf = KFold(n_splits=10)
#for train_index, test_index in kf.split(X):
#    X_train, X_test = X[train_index], X[test_index]
#    y_train, y_test = y[train_index], y[test_index]

In [6]:
#define the model
model = Sequential()
model.add(Dense(8, activation='relu', input_shape=(96,)))
model.add(Dense(16, activation='relu'))


model.add(Dense(32, activation='relu'))
#model.add(Dense(16, activation='relu', use_bias=False,kernel_regularizer=regularizers.l2(0.0001),
#               bias_regularizer='l2', activity_regularizer='l2'))

#model.add(Dense(8, activation='relu', use_bias=False,kernel_regularizer=regularizers.l2(0.0001),
#               bias_regularizer='l2', activity_regularizer='l2'))
#model.add(Dense(16, activation='relu', use_bias=False,kernel_regularizer=regularizers.l2(0.0001),
#               bias_regularizer='l2', activity_regularizer='l2'))

model.add(Dense(5, activation='softmax'))

In [7]:
#complie
opt = optimizers.SGD(learning_rate=0.001, momentum = 0.8)
#opt = optimizers.RMSprop(learning_rate=0.01, momentum = 0.8)
model.compile(opt, loss='sparse_categorical_crossentropy', metrics=['Accuracy'])

In [8]:
#fit the model
model.fit(X, y, epochs=200, validation_split = 0.2, batch_size=100, verbose=2)

Epoch 1/200
256/256 - 0s - loss: 5.0873 - Accuracy: 0.4098 - val_loss: 1.4924 - val_Accuracy: 0.4038 - 473ms/epoch - 2ms/step
Epoch 2/200
256/256 - 0s - loss: 1.4626 - Accuracy: 0.4107 - val_loss: 1.4429 - val_Accuracy: 0.4038 - 160ms/epoch - 625us/step
Epoch 3/200
256/256 - 0s - loss: 1.4258 - Accuracy: 0.4107 - val_loss: 1.4146 - val_Accuracy: 0.4038 - 162ms/epoch - 631us/step
Epoch 4/200
256/256 - 0s - loss: 1.4037 - Accuracy: 0.4107 - val_loss: 1.3967 - val_Accuracy: 0.4038 - 162ms/epoch - 633us/step
Epoch 5/200
256/256 - 0s - loss: 1.3894 - Accuracy: 0.4107 - val_loss: 1.3847 - val_Accuracy: 0.4038 - 158ms/epoch - 615us/step
Epoch 6/200
256/256 - 0s - loss: 1.3797 - Accuracy: 0.4107 - val_loss: 1.3764 - val_Accuracy: 0.4038 - 160ms/epoch - 625us/step
Epoch 7/200
256/256 - 0s - loss: 1.3730 - Accuracy: 0.4107 - val_loss: 1.3705 - val_Accuracy: 0.4038 - 161ms/epoch - 627us/step
Epoch 8/200
256/256 - 0s - loss: 1.3684 - Accuracy: 0.4107 - val_loss: 1.3663 - val_Accuracy: 0.4038 - 164

Epoch 65/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 167ms/epoch - 651us/step
Epoch 66/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3531 - val_Accuracy: 0.4038 - 159ms/epoch - 621us/step
Epoch 67/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 157ms/epoch - 613us/step
Epoch 68/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 165ms/epoch - 643us/step
Epoch 69/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 159ms/epoch - 621us/step
Epoch 70/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 162ms/epoch - 633us/step
Epoch 71/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3529 - val_Accuracy: 0.4038 - 165ms/epoch - 645us/step
Epoch 72/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3529 - val_Accuracy: 0.

Epoch 129/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 164ms/epoch - 641us/step
Epoch 130/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 161ms/epoch - 629us/step
Epoch 131/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 164ms/epoch - 639us/step
Epoch 132/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 166ms/epoch - 647us/step
Epoch 133/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 163ms/epoch - 635us/step
Epoch 134/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 165ms/epoch - 643us/step
Epoch 135/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 159ms/epoch - 621us/step
Epoch 136/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accu

256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 159ms/epoch - 621us/step
Epoch 193/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 162ms/epoch - 633us/step
Epoch 194/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3531 - val_Accuracy: 0.4038 - 158ms/epoch - 617us/step
Epoch 195/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3531 - val_Accuracy: 0.4038 - 158ms/epoch - 615us/step
Epoch 196/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3529 - val_Accuracy: 0.4038 - 165ms/epoch - 645us/step
Epoch 197/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3529 - val_Accuracy: 0.4038 - 164ms/epoch - 639us/step
Epoch 198/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 - 159ms/epoch - 621us/step
Epoch 199/200
256/256 - 0s - loss: 1.3548 - Accuracy: 0.4107 - val_loss: 1.3530 - val_Accuracy: 0.4038 -

In [9]:
# evaluate the model
loss = model.evaluate(X, y, verbose=True)

998/998 [==============================] - 0s 460us/step - loss: 1.3544 - Accuracy: 0.4093


In [10]:
prediction = model.predict(X_test)
print(prediction)

[[0.02520868 0.41231006 0.24889813 0.08758846 0.2259947 ]
 [0.02520868 0.41231006 0.24889813 0.08758846 0.2259947 ]
 [0.02520868 0.41231006 0.24889813 0.08758846 0.2259947 ]
 ...
 [0.02520868 0.41231006 0.24889813 0.08758846 0.2259947 ]
 [0.02520868 0.41231006 0.24889813 0.08758846 0.2259947 ]
 [0.02520868 0.41231006 0.24889813 0.08758846 0.2259947 ]]


In [11]:
#this is stupid
length = len(y_test)
Y_test = pd.DataFrame(y_test)
zero=[]
one=[]
two=[]
three=[]
four=[]
for i in range(length):
    if int(Y_test.iloc[i])==0:
        zero.append(1)
        one.append(0)
        two.append(0)
        three.append(0)
        four.append(0)
    elif int(Y_test.iloc[i])==1:
        zero.append(0)
        one.append(1)
        two.append(0)
        three.append(0)
        four.append(0)
    elif int(Y_test.iloc[i])==2:
        zero.append(0)
        one.append(0)
        two.append(1)
        three.append(0)
        four.append(0)
    elif int(Y_test.iloc[i])==3:
        zero.append(0)
        one.append(0)
        two.append(0)
        three.append(1)
        four.append(0)
    elif int(Y_test.iloc[i])==4:
        zero.append(0)
        one.append(0)
        two.append(0)
        three.append(0)
        four.append(1)
        
Y_test[0]=zero
Y_test[1]=one
Y_test[2]=two
Y_test[3]=three
Y_test[4]=four
roc_auc_score(Y_test.to_numpy(), prediction)#how accurate the accuracy is

0.5

In [12]:
y_pred=np.argmax(prediction, axis=1)
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[   0  192    0    0    0]
 [   0 2583    0    0    0]
 [   0 1608    0    0    0]
 [   0  565    0    0    0]
 [   0 1437    0    0    0]]
